#!/bin/bash
echo "For a molden file generated by q-chem, PRINT_ORBITALS needs to be set to a high number in order to have all virtual orbitals."
echo "PURECART = 2222 is necessary."
awk '/MOLDEN-FORMATTED INPUT FILE FOLLOWS/,/END OF MOLDEN-FORMATTED INPUT FILE/' $1 > molden.input
sed -i s/'======= END OF MOLDEN-FORMATTED INPUT FILE ======='//g  molden.input
sed -i s/'======= MOLDEN-FORMATTED INPUT FILE FOLLOWS ======='//g molden.input
sed -i s/"(Angs)"/"Angs"/g molden.input 
sed -i s/"S  "/"s  "/g     molden.input 
sed -i s/"P  "/"p  "/g     molden.input 
sed -i s/"D  "/"d  "/g     molden.input 
sed -i s/"F  "/"f  "/g     molden.input 
sed -i s/"G  "/"g  "/g     molden.input 
sed -i s/"Sp  "/"sp  "/g   molden.input 
sed -i s/"="/"= "/g        molden.input 
if grep -q "Beta" molden.input
then
 echo "Unrestricted"
else
 echo "Restricted"
 sed -i s/"Occup= 1"/"Occup= 2"/g molden.input   
fi 
